config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers:{registrations:'users/registrations'}
  resources :items do
    member do
      patch :complete
    end
  end
  root 'items#index'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user

  scope :pending, -> {
    where(completed_at: nil)
  }

  def completed?
    !completed_at.blank?
  end

  def self.to_csv(items)
    CSV.generate do |csv|
      csv << column_names
      items.each do |result|
        csv << result.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items
  has_one_attached :avatar
  before_save :attach_image
  after_create :send_email
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  def attach_image
    unless self.avatar.attachment.present?
      self.avatar.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'default_avatar.png')), 
      filename: 'default_avatar.png', 
      content_type: 'image/png')
    end
  end

  private      
  def send_email
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: [:show, :edit, :update, :destroy]

  def index
    if user_signed_in?
      @item = Item.where(:user_id => current_user.id).order("created_at DESC")
      respond_to do |format|
        format.html
        format.csv { send_data Item.to_csv(@item) }
        format.pdf do 
          render template: 'items/export_pdf',
          pdf: 'export_pdf'
        end
      end
    end
  end

  def show; end

  def new
    @item = current_user.items.build
  end

  def edit; end

  def create
    @item = current_user.items.build(item_params)
    if @item.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def update
    if @item.update(item_params)
      redirect_to root_path(@item)
    else
      render 'edit'
    end
  end

  def destroy
    @item.destroy
    redirect_to root_path
  end

  def complete
    @item = Item.find(params[:id])
    @item.update_attribute(:completed_at, Time.now)
    redirect_to root_path, notice: "Task successfully completed!"
  end

  private

  def item_params
    params.require(:item).permit(:title, :description)
  end

  def find_item
    @item = Item.find(params[:id])
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name, :description, :password, :password_confirmation, :avatar])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :name, :description, :password, :password_confirmation, :avatar])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= simple_form_for @item do |f| %>
  <%= f.input :title, required: true %>
  <%= f.input :description, required: true %>
  <%= f.button :submit, "Create task", class: "btn btn-info" %>
<% end %>

app/views/items/_static_landing_page.html.erb
<div class="jumbotron col-md-8 col-md-offset-2">
  <h2>Welcome to your Todo app</h2>
  <p>Here you can make a CRUD of all your to do tasks</p>
  <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-info" %>
  <%= link_to "Log In", new_user_session_path, class: "btn btn-info" %>
</div>

app/views/items/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>Edit task</h1>

  <%= render 'form' %>
</div>

app/views/items/export_pdf.pdf.erb
<!DOCTYPE html>
<html>
<head>
<title>List of to do tasks</title>
  <meta charset="UTF-8">
  <%= wicked_pdf_stylesheet_link_tag 'pdf' %>
</head>
<body>
  <h1 style="text-align: center;">List of to do tasks</h1>
  <% @item.each do |item| %>
    <% if item.completed? %>
      <h3><strike><%= item.title %></strike></h3>
      <p><%= item.description %></p>
    <% else %>
      <h3><%= item.title %></h3>
      <p><%= item.description %></p>
    <% end %>
  <% end %>
</body>
</html>

app/views/items/index.html.erb
<% if user_signed_in? %>
  <div class="col-md-6 col-md-offset-3">
    <%= link_to("Export to CSV", items_path(format: :csv), class: "btn btn-info") %>
    <%= link_to("Export to PDF", items_path(@items, format: :pdf), class: "btn btn-info") %>
		<% @item.each do |item| %>
			<div class="index-wrapper">
				<% if item.completed? %>
          <div class="row item">          
						<div class="col-md-8">
							<h2 style="opacity: 0.5;" class="item-title"><strike><%=item.title %></strike></h2>
							<p style="opacity: 0.5;" class="item-sub-title item-desc"><%= item.description %></p>
							<p style="opacity: 0.5;" class="time-created-at item-sub-title">Completed <%= time_ago_in_words(item.completed_at) %> ago</p>
            </div>
						<div class="col-md-2">
							<p><%= link_to complete_item_path(item), method: :patch do %></p>
								<i class="fa fa-check fa-lg"></i>
							<% end %>
            </div>

						<div class="col-md-2">
							<p><%= link_to item, method: :delete, data: { confirm: "Are you sure?" } do %></p>
								<i class="fa fa-trash fa-lg"></i>
							<% end %>
            </div>	
          </div>
          
        <% else %>	
          <div class="row item">
          
						<div class="col-md-8">
							<h2 class="item-title"><%= link_to item.title, item %></h2>
							<p class="item-sub-title item-desc"><%= item.description %></p>
							<p style="opacity: 0.5;" class="time-created-at item-sub-title">Created <%= time_ago_in_words(item.created_at) %> ago</p>
            </div>
            
						<div class="col-md-2">
							<p><%= link_to complete_item_path(item), method: :patch do %></p>
								<i class="fa fa-check fa-lg"></i>
							<% end %>
            </div>
            
						<div class="col-md-2">
							<p><%= link_to item, method: :delete, data: { confirm: "Are you sure?" } do %></p>
								<i class="fa fa-trash fa-lg"></i>
							<% end %>
            </div>
            
					</div>
        <% end %>
      </div>
    <% end %>	
  </div>
<% else %>
	<%= render 'static_landing_page' %>
<% end %>	

app/views/items/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>New task</h1>

  <%= render 'form' %>
</div>

app/views/items/show.html.erb
<div class="col-md-6 col-md-offset-3">  
  <h2><%= @item.title %></h2>
  <p><%= @item.description %></p>

  <%= link_to "Edit", edit_item_path(@item), class: "btn btn-info" %>
	<%= link_to "Delete", item_path(@item), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-info" %>
  <%= link_to "Back", root_path, class: "btn btn-info" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo app</title>
    <link rel="icon" href="../../assets/images/todo_app_icon.ico">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"></link>
  </head>
  <body>

    <nav class="navbar navbar-default" style="background: #EFF5FC;">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Todo App", root_path, class: "navbar-brand" %>
        </div>
        <ul class="nav navbar-nav">
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% if current_user.present? %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
          <% else %>
            <li><%= link_to "Log In", new_user_session_path %></li>
          <% end %>
        </ul>
        <% if user_signed_in? %>
          <div class="navbar-right">
            <span><%= image_tag current_user.avatar, style: 'width:40px; border-radius: 50%;' %></span>
            <span><%= link_to "New Task", new_item_path, class: "navbar-text navbar-link" %></span>
            <span><%= link_to "Edit Profile", edit_user_registration_path, class: "navbar-text navbar-link" %></span>
          </div>
        <% end %>
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>